tasks/master.yml

The other references to `named-checkzone` don't include `/sbin`; this just makes the calls consistent.

Find named-checkzone in path on CentOS 6

---

templates/bind_zone.j2
templates/reverse_zone.j2

It's sometimes useful to provide aliases for external hosts; requires a `forwarders` entry in `/etc/named.conf` to be useful (which I haven't added).

Allow CNAME-only records

---

IDEMPOTENT_ZONEFILES.md
tasks/main.yml
templates/bind_zone.j2
templates/reverse_zone.j2
templates/reverse_zone_ipv6.j2

I have made some changes to the zonefile templates to make them idempotent during each execution.
They will only get re-generated if the data in them genuinely changes, rather than every time, because of the serial.
Was created from an idea noted in the following article:
https://linuxmonk.ch/wordpress/index.php/2016/managing-dns-zones-with-ansible/

Idempotent Zonefiles

---

README.md
defaults/main.yml
templates/master_etc_named.conf.j2
templates/slave_etc_named.conf.j2

Hi Bert,
This is a little PR that allows DNSSEC to be disabled.
The use case is to setup a DNS server that acts a forwarder to AWS VPC private zone, which does not supports DNSSEC (see https://aws.amazon.com/premiumsupport/knowledge-center/r53-private-ubuntu/)
Hope this helps,
Guillaume

Make DNSSEC options configurable

---

tasks/main.yml

This changes the BIND zone serial to use UTC UNIX time, allowing updates to the records therein to happen as frequently as once per second while still propagating those updates to slave servers.
BIND's serial is any positive integer, modulo 2^32. UNIX time is 2^32 maximum (at least until we try to solve the 2038 problem), so this is safe from a bounds standpoint (and almost certainly thereafter with the modulo).
This is also safe for things currently in production so long as it's after Wed Feb 21 06:12:03 UTC 1973 (the maximum UNIX timestamp equivalent value of the current '+%y%m%d%H' timestamp).

Create serial as UTC UNIX time

---

README.md
defaults/main.yml
templates/bind_zone.j2
templates/master_etc_named.conf.j2
templates/reverse_zone.j2
templates/reverse_zone_ipv6.j2
templates/slave_etc_named.conf.j2

Noticed that some "global variables" had not been rolled into the templates in all cases for the multi-zone work.  Also pulled in the other "zone specific" configs from their "global" standpoint.   Best to do sooner, whilst people are migrating to the v4.0.0 release, to minimise migration impacts (these changes, are also not backward compatible)

Small tidy ups, tweaks, and config rationalisation.

---

tasks/main.yml

when domain file is not yet created, then grep was complaining and role failed. Tested with ansible 2.4.3 against Ubuntu 14.4

Fixes issue with non-existing file when grepping domain

---

templates/master_etc_named.conf.j2
templates/slave_etc_named.conf.j2

Have just needed to carry out some subdomain delegations, and found that the configuration defined by the role was not fully functioning.  Have applied tweaks to make the require zone-level "forwarder overrides".

handle delegation, wrt forwarding.

---

README.md
templates/bind_zone.j2

Introduce optional `type` attribute to `aliases` to allow DNAME records.

add support for DNAME record type

---

README.md
templates/master_etc_named.conf.j2

Hi Bertie,
I've used your module which saved me a bunch of time but I found the need for some extra channel logging.
I've implemented it in this PR.
This provides a generic ability to setup extra logging for the service.
```
bind_other_logs:
- name: lame-servers
file: data/lame-servers.log
versions: 3
size: "5m"
- name: security
file: data/security.log
versions: 10
size: "10m"
```
Let me know what you think ...

Extend to give possibility of configuring extra logging channels.

---

.travis.yml
README.md
tasks/main.yml
tasks/master.yml
templates/bind_zone.j2
templates/master_etc_named.conf.j2
templates/reverse_zone.j2
templates/reverse_zone_ipv6.j2
templates/slave_etc_named.conf.j2

ISC bind9 ARM [the $GENERATE Directive](https://ftp.isc.org/isc/bind9/cur/9.12/doc/arm/Bv9ARM.ch05.html#generate_directive) and http://www.zytrax.com/books/dns/ch8/generate.html
Add support for using `$GENERATE` to facilitate iterative records creation.
Examples:
```
- name: '$GENERATE 1-5 ww$'
ip: 172.21.12.$
```
```
- name: 'dev-srv001'
ip: 172.21.12.9
aliases:
- '$GENERATE 3-9  wwwdev$'
- '$GENERATE 3-9  ftp$'
```
```
- name: '$GENERATE 32-96 g$'
ip: 172.21.99.$
aliases:
- '$GENERATE 32-96  guest-dhcp-$'
```

WIP: Add support for the $GENERATE Directive

---

tasks/slave.yml

This is necessary because this directory is hard-coded in the slave_etc_named.conf.j2 template.
For Red Hat based distros this directory is created by default with bind package installation:
$ ls -alhdZ /var/named/slaves/
drwxrwx---. named named system_u:object_r:named_cache_t:s0 /var/named/slaves/
But for Debian based distributions the directory is not created at all.

Ensure directory for cached slaves zones

---

tasks/main.yml

Use defined variable that's OS dependent (affects binding keys)

tasks: main: use bind_group for group

---

templates/master_etc_named.conf.j2
templates/slave_etc_named.conf.j2

dnssec-lookaside: 'auto' is removed now from bind.
It is a quick fix to make it working again.
"The ISC DNSSEC Lookaside Validation (DLV) service has been shut down; all DLV records in the dlv.isc.org zone have been removed. References to the service have been removed from BIND documentation. Lookaside validation is no longer used by default by delv. The DLV key has been removed from bind.keys. Setting dnssec-lookaside to auto or to use dlv.isc.org as a trust anchor results in a warning being issued."
https://ftp.isc.org/isc/bind9/9.9.12/RELEASE-NOTES-bind-9.9.12.html
Should we make it configurable?

Removes dnssec-lookaside from master/slave configurations

---

README.md
templates/master_etc_named.conf.j2

Use a dict to specify filename, number for versions to keep and file size.
This is compatible with old behaviour where only filename was defined.

allow specify versions and size for query log files

---

templates/slave_etc_named.conf.j2

In #105 the bind_query_log option was enhanced to make version and size configurable. This feature was missing for slave instances.
This patch to the template for slave servers fixes it.

Fix querylog version & size setting for slave

---

.travis.yml
README.md
molecule/default/converge.yml
molecule/default/files/dns.bats
molecule/default/files/functional-tests.sh
molecule/default/molecule.yml
molecule/default/verify.yml

Instead of complex scripts in order to create Docker containers, Molecule allows developers to easily and quickly test their roles  by automatically creating containers which are configured by readable yaml configuration files. Molecule does this by leveraging Ansible's [docker_container](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html) module. 
The proposed Molecule configuration is essentially the automated version of the docker_tests branch, all done with a single command! An example of a working .travis.yml file is also provided. 
In **molecule.yml**, two Centos 7 containers are defined which will fulfill the master and slave role. The images are specifically chosen as they are Ansible compatible and can run systemd in them. Any Ansible/Systemd compatible …

Replace manual Docker tests with Molecule

---

README.md
defaults/main.yml
meta/main.yml
templates/master_etc_named.conf.j2
templates/slave_etc_named.conf.j2
vars/Archlinux.yml
vars/Debian.yml
vars/FreeBSD.yml
vars/RedHat.yml

Adds support for FreeBSD to the BIND role:
* Removed the long list of supported operating systems as it's getting
unmanagable.
* Alphabetically sorted platforms in meta to make it easier as more platforms
are added.
* Turned the slave directory, bindkeys-file, pid-file and session-keyfile into
variables.

Add FreeBSD support

---

tasks/main.yml

As proposed in https://github.com/bertvv/ansible-role-bind/issues/114,
this moves the auth transfer template task to be executed
before the master slave setup tasks.

Fix master/slave with key error

---

README.md
tasks/main.yml
templates/auth_transfer.j2

Hi,
it would be a great feature to let one use a defined TSIG key to sign zone transfer reuqests, especially in environments where you do not control the master node yourself. This allows the other side to not use the servers IP for athorization but the TSIG key.
At the moment, all defined TSIG keys (`bind_dns_keys`) are only used locally.
The proposed feature adds another variable, `bind_transfer_key_name`. If set, this variable will add a server statement to <confdir>/auth_transfer.conf that tells bind to sign all requests to `bind_zone_master_ip` with said TSIG key.
Before changing any configuration, a check is performed if the supplied transfer key is present in the `bind_dns_keys` dict. This check is case sensitive, as it is in bind9 itself.
The change only affects slave nodes, as …

New feature: sign zones with TSIG key for XFR

---

.github/workflows/ci.yml

Following upgrade of upstream molecule to 3.1.1, current molecule configuration breaks.
Specify molecule version explicitly (3.0.8), till we have a working solution.

Relates to #135. Specify molecule version explicitly

---

README.md
defaults/main.yml
vars/Debian.yml
vars/RedHat.yml

Hi,
this change allows users of the role to use python3 instead of python2.
It introduces the `bind_python_version`. Its defaults are taken over from the defaults formerly used (in RedHat and Debian).
Kind regards

Added switch to choose python version

---

templates/etc_named.conf.j2

Hi,
in bind9.16, there are some changes to the config file.
One breaking change for this module is the removal of `dnssec-enable` - the config parser throws an error about the parameter.
This patch removes this config parameter if it is unset. To unset it, add
`bind_dnssec_enable: ~`
There are additional changes, documented [here](http://ddiguru.com/blog/bind-9-16-release-info).
A suggested update for the defaults would be setting `bind_dnssec_validation` to `auto`, as a specific trust anchor is required if set to `true` (current default).
Kind regards

Fixed config template for bind9 16

---

README.md
defaults/main.yml
tasks/main.yml
templates/auth_transfer.j2

Hi,
this is the v5 update for #121 .
A dictionary has been added, 'bind_key_mapping' to map hosts (primaries or secondaries - doesn't matter) to TSIG keys.
Kind regards

configure TSIG keys for notify/update queries

---

templates/reverse_zone_ipv6.j2

IPv6 reverse addresses did not get created due to missing escape of a forward slash and missing colon.

corrected regex, so that IPv6 reverse DNS entries get created correctly

---

templates/etc_named.conf.j2

Hi,
I've noticed a cosmetic bug regarding Jinja if-block indents in [named.conf template](https://github.com/bertvv/ansible-role-bind/blob/master/templates/etc_named.conf.j2)
This PR is just to fix the indents to make the block statements nicely aligned.
Example before:
```
logging {
channel default_debug {
file "data/named.run";
severity dynamic;
print-time yes;
};
channel querylog {
file "data/query.log" versions 10 size 10m;
severity dynamic;
print-time yes;
};
category queries { querylog; };
};
```
Example after:
```
logging {
channel default_debug {
file "data/named.run";
severity dynamic;
print-time yes;
};
channel querylog {
file "data/query.log" versions 10 size 10m;
severity dynamic;
print-time yes;
};
category queries { querylog; };
};
```
This is actually my first PR, so …

Fix Jinja block indent in querylog
